### ISSUE TITLE
Import "numproto/protobuf/ndarray.proto" has not been loaded

### ISSUE THREAD

**Issue by secretlyvogon** [xainag/numproto#17]
I am trying to implement a simple application where I send a numpy array and receive the flattened value array. My proto file is given below:

```
syntax = "proto3";

import "numproto/protobuf/ndarray.proto";

message npArray{
        numproto.protobuf.NDArray array = 1;
}

service FlattenArray{
        rpc flatten_numpy(npArray) returns (npArray){}
}
```

I am using the python grpc-tools command as suggested in the readme. Since I am using an anaconda environment, I changed the `site-packages` location to the one where anaconda would install it. It is able to run and the files flatten_numpy_pb2.py and flatten_numpy_pb2_grpc.py are created without error. However, as soon as I run the server script, it gives me the error showing that the import wasn't done.

The entire stack trace is as follows:

```
Traceback (most recent call last):
  File "flatten_server.py", line 7, in <module>
    import flatten_numpy_pb2
  File "/home/saket/grpc_test/flatten_numpy_pb2.py", line 24, in <module>
    dependencies=[numproto_dot_protobuf_dot_ndarray__pb2.DESCRIPTOR,])
  File "/home/saket/anaconda3/envs/test/lib/python3.6/site-packages/google/protobuf/descriptor.py", line 884, in __new__
    return _message.default_pool.AddSerializedFile(serialized_pb)
TypeError: Couldn't build proto file into descriptor pool!
Invalid proto descriptor for file "flatten_numpy.proto":
  numproto/protobuf/ndarray.proto: Import "numproto/protobuf/ndarray.proto" has not been loaded.
  npArray.array: "numproto.protobuf.NDArray" seems to be defined in "ndarray.proto", which is not imported by "flatten_numpy.proto".  To use it here, please add the necessary import.
```

**Comment by JBLanier** [comment]
I'm having the same issue, were you able to resolve it?

**Comment by secretlyvogon** [comment]
@JBLanier  Yes and no. There may be something wrong with the library, because of which it isn't working as intended. The serialize/deserialize functions still work properly. You could use those to convert your numpy arrays into bytes and create your own proto file with `byte` type message. I didn't need the library after that.

**Comment by JBLanier** [comment]
@secretlyvogon Thanks. Yeah, I also couldn't find the issue with the library (if there is one), but the code is simple enough to integrate it into one's own package as you said.

**Comment by mckinziebrandon** [comment]
Also having this issue.

**Comment by akashmehra** [comment]
I am also having the same issue.

**Comment by Robert-Steiner** [comment]
Hi @secretlyvogon, 

the issue occurs if python uses the C++ implementation and not the python implementation of the proto files. You can find more about the issue [here](https://github.com/protocolbuffers/protobuf/issues/3002). One workaround is to set the 
the environment variable `PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION='python'` before you start your python program. 

You can also check out our `xain-proto` repository which provides the numproto files as well. Here you shouldn't get the error, since we changed the way how we generate the proto files.
